apiVersion: v1
kind: PersistentVolume
metadata:
  name: asses1-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName : local-storage
  local : 
    fsType : ext4
    path : /asses1-code
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: agentpool
          operator: In
          values:
          - default